version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

formats: all

# Optionally declare the Python requirements required to build your docs
python:
   install:
     - method: pip
       path: .
       extra_requirements:
         - docs
